### ISSUE TITLE
Fireballs persist on screen until they run into an object or a slope

### ISSUE THREAD

**Issue by GameguySD** [Addikins/RPG-Tech-Demo#7]

**Comment by Addikins** [comment]
They should, as all projectiles, have a certain time limit until death. Perhaps that time limit is too high. I'll check to see if reducing it improves gameplay, and I'll check on my side that it does eventually destroy itself as it should.

**Comment by Addikins** [comment]
Enemy Fireball Max Life Time reduced from 5 seconds to 2.5
